export const BIGFOOT_HOME_URL = 'https://bigfoot.capital/'
export const BIGFOOT_DOCS_URL = 'https://bigfoot.capital/bigfootMD/'
export const BIGFOOT_PRODUCT_BOARD_URL = 'https://bigfoot.capital/'
export const BIGFOOT_GITHUB_DISCUSSIONS_URL = 'https://github.com/yatstudio/bigfootMD/discussions'
export const BIGFOOT_GITHUB_CONTRIBUTING_URL = 'https://github.com/yatstudio/bigfootMD/blob/main/CONTRIBUTING.md'
export const BIGFOOT_GITHUB_ISSUES_URL = 'https://github.com/yatstudio/bigfootMD/issues'
export const BIGFOOT_GITHUB_PULL_REQUESTS_URL = 'https://github.com/yatstudio/bigfootMD/pulls'
